# Generated by Django 5.0.4 on 2024-06-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='No category', max_length=100),
            preserve_default=False,
        ),
    ]
