# Generated by Django 5.0.4 on 2024-06-21 19:25
import random
from django.db import migrations


class Migration(migrations.Migration):

    def add_barcodes(apps, schema_editor):
        Product = apps.get_model(app_label='main_app', model_name='Product')
        all_products = Product.objects.all()
        all_barcodes = random.sample(range(100_000_000, 1_000_000_000), len(all_products))
        for i in range(len(all_products)):
            product = all_products[i]
            product.barcode = all_barcodes[i]
            product.save()

    def reverse_barcodes(apps, schema_editor):
        Product = apps.get_model(app_label='main_app', model_name='Product')
        for product in Product.objects.all():
            product.barcode = 0
            product.save()

    dependencies = [
        ('main_app', '0006_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcodes, reverse_code=reverse_barcodes)
    ]
