# Generated by Django 5.1.1 on 2024-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pets_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
