# Generated by Django 5.0.4 on 2024-06-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], max_length=20),
        ),
    ]
