# Generated by Django 5.0.4 on 2024-07-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_laptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='operating_system',
            new_name='operation_system',
        ),
    ]
