# Generated by Django 5.0.4 on 2024-07-15 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_foodcriticrestaurantreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularrestaurantreview',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterUniqueTogether(
            name='foodcriticrestaurantreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='regularrestaurantreview',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('reviewer_name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Review',
                'verbose_name_plural': 'Restaurant Reviews',
                'ordering': ['-rating'],
                'abstract': False,
                'unique_together': {('reviewer_name', 'restaurant')},
            },
        ),
        migrations.AddField(
            model_name='foodcriticrestaurantreview',
            name='restaurantreview_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.restaurantreview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularrestaurantreview',
            name='restaurantreview_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.restaurantreview'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='foodcriticrestaurantreview',
            name='id',
        ),
        migrations.RemoveField(
            model_name='foodcriticrestaurantreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='foodcriticrestaurantreview',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='foodcriticrestaurantreview',
            name='review_content',
        ),
        migrations.RemoveField(
            model_name='foodcriticrestaurantreview',
            name='reviewer_name',
        ),
        migrations.RemoveField(
            model_name='regularrestaurantreview',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regularrestaurantreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='regularrestaurantreview',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='regularrestaurantreview',
            name='review_content',
        ),
        migrations.RemoveField(
            model_name='regularrestaurantreview',
            name='reviewer_name',
        ),
        migrations.CreateModel(
            name='MenuReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('review_content', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.menu')),
            ],
            options={
                'verbose_name': 'Menu Review',
                'verbose_name_plural': 'Menu Reviews',
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['menu'], name='main_app_menu_review_menu_id')],
                'unique_together': {('reviewer_name', 'menu')},
            },
        ),
    ]
