# Generated by Django 5.1.2 on 2024-10-25 08:53

import django.core.validators
import django.db.models.deletion
import fruitipedia_exam_prep.fruits_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This fruit name is already in use! Try a new one.'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_exam_prep.fruits_app.validators.OnlyLettersValidator()], verbose_name='Name')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('nutrition', models.TextField(blank=True, null=True, verbose_name='Nutrition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile', verbose_name='Owner')),
            ],
        ),
    ]
