# Generated by Django 5.1.2 on 2024-10-26 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'We already have a recipe with the same title!'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Recipe')),
                ('cuisine_type', models.CharField(choices=[('French', 'French'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Balcan', 'Balcan'), ('Other', 'Other')], max_length=7, verbose_name='Cuisine Type')),
                ('ingredients', models.TextField(help_text='Ingredients must be separated by a comma and space.', verbose_name='Ingredients')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('cooking_time', models.PositiveIntegerField(help_text='Provide the cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking Time')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='profile_app.profile', verbose_name='Author')),
            ],
        ),
    ]
