# Generated by Django 5.1.2 on 2024-10-26 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(error_messages={'unique': 'We already have a recipe with the same title!'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Title'),
        ),
    ]
