# Generated by Django 5.1.2 on 2024-10-25 08:42

import django.core.validators
import fruitipedia_exam_prep.profile_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_exam_prep.profile_app.validators.FirstLetterValidator()], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), fruitipedia_exam_prep.profile_app.validators.FirstLetterValidator()], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('password', models.CharField(help_text='*Password length requirements: 8 to 20 characters', max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
