# Generated by Django 5.1.2 on 2024-10-27 07:36

import django.core.validators
import furry_funnies_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), furry_funnies_app.common.validators.OnlyLettersValidator()], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), furry_funnies_app.common.validators.OnlyLettersValidator()], verbose_name='Last Name')),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits', max_length=6, validators=[furry_funnies_app.common.validators.PasscodeDigitsCountValidator()], verbose_name='Passcode')),
                ('pets_number', models.PositiveSmallIntegerField(verbose_name='Pets Number')),
                ('info', models.TextField(verbose_name='Info')),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
        ),
    ]
