# Generated by Django 5.1.2 on 2024-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
