# Generated by Django 5.1.2 on 2024-10-27 12:34

import furry_funnies_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_image_url_alter_author_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[furry_funnies_app.common.validators.PasscodeDigitsCountValidator()], verbose_name='Passcode'),
        ),
    ]
